### ISSUE TITLE
needLargeMem error when using fetch with bins

### ISSUE THREAD

**Issue by maxwellsh** [nvictus/pybbi#14]
Hi Nezar,
I think this might be a problem with the original C library, but I am curious if you have ever seen the following error before, if you have theories as to why it's happening, and any suggestions to circumvent the problem. I am attempting to extract a 50kb region into 100 bins from a standard bigwig file downloaded from ENCODE.

The following commands work as expected:
>>> x = bbi.fetch('ENCFF089CVK.bigWig', 'chr8', 146250000, 146300000)
>>> x = bbi.fetch('ENCFF089CVK.bigWig', 'chr8', 146250000, 146300000, bins=1000)

However, when I decrease the number of bins to 156 or fewer, the python interpreter dies without throwing an exception and the following message is printed to the terminal:
>>> x = bbi.fetch('ENCFF089CVK.bigWig', 'chr8', 146250000, 146300000, bins=156)
needLargeMem: trying to allocate 18446744069414602975 bytes (limit: 17179869184)

Thanks for your insight,
Max

**Comment by nvictus** [comment]
Hi Max!

I think it's exactly this issue I raised a few months ago: https://github.com/ucscGenomeBrowser/kent/issues/25

They weren't able to track down the exact source, but it might be worth re-opening there.

**Comment by maxwellsh** [comment]
How odd! I'll give the issue a bump over at UCSC.
In the meantime, I'll take your approach of binning within python.

Thanks, Nezar!
